version: "3.9"
services:
  frontend:
    build: .
    volumes:
      - ./:/usr/src/app
      - nodemodules:/usr/src/app/node_modules
    ports:
      - "3330:3000"
    environment:
      - API_URL=http://localhost:3333/
      - APP_CLIENT_KEY=7BpSpC4q8gg2QSR
      - CLUB_APP_URL=https://private.stg.globalclub.it
      - COUNTRIES_API_URL=https://restcountries.eu/rest/v2/all
      - FAVICON_VERSION=Lbxoegj4RJ
      - HOST=0.0.0.0
      - PORT=3000
      - NEWS_APP_URL=https://news.stg.globalgroup.consulting
      - NODE_ENV=development
      - NODE_OPTIONS=--max-old-space-size=4096
      - NPM_CONFIG_PRODUCTION=false
      - PROVINCES_API_URL=https://comuni-ita.herokuapp.com/api/province
      - REGIONS_API_URL=https://comuni-ita.herokuapp.com/api/regioni
      - SOCKET_URL=wss://localhost:3333
volumes:
  nodemodules: { }
